// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {ai} from '../models';

export function GenerateSlug(arg1:string):Promise<string>;

export function GetAISetting():Promise<domain.AISetting>;

export function GetBuiltInModels():Promise<Array<string>>;

export function GetProviderRegistry():Promise<Array<ai.ProviderInfo>>;

export function ListProviderModels(arg1:string,arg2:string):Promise<Array<string>>;

export function SaveAISettingFromFrontend(arg1:domain.AISetting):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<void>;
