// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSlug(arg1) {
  return window['go']['facade']['AIFacade']['GenerateSlug'](arg1);
}

export function GetAISetting() {
  return window['go']['facade']['AIFacade']['GetAISetting']();
}

export function GetBuiltInModels() {
  return window['go']['facade']['AIFacade']['GetBuiltInModels']();
}

export function GetProviderRegistry() {
  return window['go']['facade']['AIFacade']['GetProviderRegistry']();
}

export function ListProviderModels(arg1, arg2) {
  return window['go']['facade']['AIFacade']['ListProviderModels'](arg1, arg2);
}

export function SaveAISettingFromFrontend(arg1) {
  return window['go']['facade']['AIFacade']['SaveAISettingFromFrontend'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['facade']['AIFacade']['TestConnection'](arg1, arg2, arg3);
}
