// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadThemeConfig() {
  return window['go']['facade']['ThemeFacade']['LoadThemeConfig']();
}

export function LoadThemes() {
  return window['go']['facade']['ThemeFacade']['LoadThemes']();
}

export function SaveThemeConfig(arg1) {
  return window['go']['facade']['ThemeFacade']['SaveThemeConfig'](arg1);
}

export function SaveThemeConfigFromFrontend(arg1) {
  return window['go']['facade']['ThemeFacade']['SaveThemeConfigFromFrontend'](arg1);
}

export function SaveThemeCustomConfigFromFrontend(arg1) {
  return window['go']['facade']['ThemeFacade']['SaveThemeCustomConfigFromFrontend'](arg1);
}

export function SetRenderer(arg1) {
  return window['go']['facade']['ThemeFacade']['SetRenderer'](arg1);
}

export function UploadThemeCustomConfigImage(arg1) {
  return window['go']['facade']['ThemeFacade']['UploadThemeCustomConfigImage'](arg1);
}
