// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {facade} from '../models';

export function LoadThemeConfig():Promise<domain.ThemeConfig>;

export function LoadThemes():Promise<Array<domain.Theme>>;

export function SaveThemeConfig(arg1:domain.ThemeConfig):Promise<void>;

export function SaveThemeConfigFromFrontend(arg1:domain.ThemeConfig):Promise<void>;

export function SaveThemeCustomConfigFromFrontend(arg1:Record<string, any>):Promise<void>;

export function SetRenderer(arg1:facade.RendererFacade):Promise<void>;

export function UploadThemeCustomConfigImage(arg1:string):Promise<string>;
